### ISSUE TITLE
Bug: Frontend and Backend do not properly handle when the Chatgpt API Key is not present

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/json-to-typescript-chatgpt#1]
Readme does not explain how to put in the chatgpt api key.

When running the system without it, the frontend does not return any indication of an error in the backend.

Here is the following error on the server side that was output to the console.

[error.txt](https://github.com/novuhq/json-to-typescript-chatgpt/files/10956793/error.txt)

**Comment by SameerVanjari** [comment]
This can be solved by using it as a _environment_ variable in the `.env` file. 
I'll create a PR for this and then you can merge it.

**Comment by mubarak23** [comment]
Here is a Pull Request with respect to this
https://github.com/novuhq/json-to-typescript-chatgpt/pull/2
@SameerVanjari
